config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
    resources :posts do
        resources :comments
    end
    root "posts#index"
    get '/about', to: "page#about"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :title, presence: true, length: { minimum: 2 }
    validates :body, presence: true, length: { maximum: 350 }
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
        @post = Post.find(params[:post_id])
        @comment = @post.comments.create(params[:comment].permit(:name, :body))
        
        redirect_to post_path(@post)
    end
    
    def edit
    end
    def destroy
        @post = Post.find(params[:post_id])
        @comment = @post.comments.find(params[:id])
        @comment.destroy
        redirect_to post_path(@post)
        
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
    def about
    end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def show
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to posts_path
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment cfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> ago</p>

	</div>
	<% if user_signed_in? %>
		<p><%= link_to 'Delete', [comment.post, comment], method: :delete, class: "buttons",
		data: {confirm: 'Are you sure you want to delete?'} %></p>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
    <p>
        <%= f.label :name %><br>
        <%= f.text_field :name %>
    </p>
    
    <p>
        <%= f.label :content %><br>
        <%= f.text_area :body %>
        
    </p>
    <br>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="bar">
    <div id="logo">
      <%= link_to root_path do %>
        <%= image_tag "SFU logo.jpg" %>
      <% end %>
    </div>
  

 
    <ul>
        <li class ="category">Louis's Website</li>
        <a href="https://github.com/LouisJHC/">GitHub</a></li>
        <li><%= link_to "Blog", root_path %></li>
        <li><%= link_to "About", about_path %></li>
    
   </ul>
   <% if !user_signed_in? %>
    <p class="sign_in">Adminstrator Login</p>
  <% end %>
  </div>
  
  <div id="main">
    <div id="header">
      <% if current_page?(root_path) %>
				<p>Posts</p>
			<% elsif current_page?(about_path) %>
				<p>About</p>
			<% else %>
				<%= link_to "Back to Posts", root_path %>
			<% end %>
      
      <% if user_signed_in? %>
      
      <div class="buttons">
        <button class="button"><%= link_to "New Post", new_post_path %>
        <button class="button">
          Log Out
        </button></button>
      </div>
    <% end %>
    </div>
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert") %>
      <%end %>

<%= yield %>
</div>

</body>
</html>

app/views/page/about.html.erb
<div id="wrappingpage">
    <div id="content">
        <h1> Hi all, my name is Louis Cha. I'm a third year Computer Science student at Simon Fraser University.</h1>
        <h1> Welcome to my blog!</h1>
    </div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
    <% if @post.errors.any? %>
        <div id="error"></div>
            <h2><%= pluralize(@post.errors.count, "error") %> exists. Please check again.</h2>
            <ul>    
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
    <% end %>
    <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    </p>
    
    <p>
        <%= f.label :content %><br>
        <%= f.text_area :body %>
        
    </p>
    
    <p>
        <%= f.submit %>
    </p>
<% end %>
</div>

app/views/posts/edit.html.erb
<div id="pagewrapping">
<h1>Edit</h1>

<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |p| %>
    <div class= "wrappingpost">
        
        <h1 class="title"><%= link_to p.title, p %></h1>
        <p class="date"><%= p.created_at.strftime("%B, %d, %Y") %></p>
    </div>

<% end %>

app/views/posts/new.html.erb
<div id="pagewrapping">
<h1>Post</h1>

<%= form_for :post, url:posts_path do |f| %>
    <% if @post.errors.any? %>
        <div id="error"></div>
            <h2><%= pluralize(@post.errors.count, "error") %> exists. Please check again</h2>
            <ul>    
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
    <% end %>
    <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
    </p>
    
    <p>
        <%= f.label :content %><br>
        <%= f.text_area :body %>
        
    </p>
    
    <p>
        <%= f.submit %>
    </p>
<% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
<h1 class="title">
    <%= @post.title %>
</h1>

<p class="date">
    Created <%= time_ago_in_words(@post.created_at) %> ago
    <% if user_signed_in? %>
        | <%= link_to 'edit', edit_post_path(@post) %>
        | <%= link_to 'delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure who want to delete?'} %>
    <% end %>
</p>

<p class="content">
    <%= @post.body %>
    <div id="comments">
        <h2><%= @post.comments.count %> Comments</h2>
        <%= render @post.comments %>
        
        <h3>Write a comment:</h3>
        <%= render "comments/form" %>
    </div>
</p>
</div>